[tox]
envlist = lint,type,test
skipsdist = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}

[testenv:lint]
deps = ruff >=0.16.0,<0.17.0
commands = ruff check .

[testenv:type]
deps =
    mypy >=2.0.0,<3.0.0
    types-requests >=2.32.0,<3.0.0
    types-PyYAML >=6.0.0,<7.0.0
    types-toml >=0.10.0,<0.11.0
commands =
    pip install .
    mypy .

[testenv:test]
deps =
    pytest >=8.2.0,<9.0.0
    pytest-cov
    pytest-asyncio >=0.25.0,<0.26.0
commands =
    pip install .
    pytest --cov=palatium_ai --cov-report=term-missing
# allowlist_externals = poetry

# === === === === === === === === === === === === === === === === 
# === Запуск всех проверок - poetry run tox                ~~ ===
# === Запуск линтинга - poetry run tox -e lint             ~~ ===
# === Запуск проверки типов - poetry run tox -e type       ~~ ===
# === Запуск тестов - poetry run tox -e test               ~~ ===                                                          
# === Запуск всех проверок - poetry run tox -e lint,type   ~~ ===                                                          
# === === === === === === === === === === === === === === === === 