# src/palatium_ai/domain/memory/consolidate_payload.py

"""Pending user-initiated extract enqueue via MCP ``consolidate_memory`` (HITL, 020/070).

Legacy tool name ``consolidate_memory`` = enqueue sleep-time **extract**
(transcript → medium). Not graph promote.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class MemoryConsolidatePayload(BaseModel):
    """Serialized ``consolidate_memory`` args awaiting HITL (extract enqueue)."""

    model_config = {"frozen": True}

    task_id: str = Field(min_length=1, max_length=128)
    thread_id: str = Field(min_length=1, max_length=128)
    user_id: str = Field(min_length=1, max_length=128)
    org_id: str = Field(default="", max_length=128)
    consolidate_task_id: str = Field(
        default="",
        max_length=128,
        description="Optional extract job id passed to MCP; empty → auto-generated by tool.",
    )
