# src/palatium_ai/domain/memory/consolidate_payload.py

"""Pending user-initiated memory consolidate (off-graph HITL commit path, 020/070)."""

from __future__ import annotations

from pydantic import BaseModel, Field


class MemoryConsolidatePayload(BaseModel):
    """Serialized consolidate_memory arguments awaiting HITL approval."""

    model_config = {"frozen": True}

    task_id: str = Field(min_length=1, max_length=128)
    thread_id: str = Field(min_length=1, max_length=128)
    user_id: str = Field(min_length=1, max_length=128)
    org_id: str = Field(default="", max_length=128)
    consolidate_task_id: str = Field(
        default="",
        max_length=128,
        description="Optional job id passed to MCP; empty → auto-generated by tool.",
    )
