# src/palatium_ai/domain/memory/extract_enqueue_payload.py

"""Pending user-initiated extract enqueue via MCP ``extract_transcript_memories`` (HITL)."""

from __future__ import annotations

from pydantic import BaseModel, Field


class MemoryExtractEnqueuePayload(BaseModel):
    """Serialized ``extract_transcript_memories`` args awaiting HITL."""

    model_config = {"frozen": True}

    task_id: str = Field(min_length=1, max_length=128)
    thread_id: str = Field(min_length=1, max_length=128)
    user_id: str = Field(min_length=1, max_length=128)
    org_id: str = Field(default="", max_length=128)
    extract_task_id: str = Field(
        default="",
        max_length=128,
        description="Optional extract job id passed to MCP; empty → auto-generated by tool.",
    )
