"""Универсальный UI/presentation-контракт ответа платформы (не агенты, не MCP)."""

from .content_document import (
    ActionKind,
    ActionSpec,
    ActionStyle,
    CalloutBlock,
    ChartBlock,
    CodeBlock,
    ContentBlock,
    ContentDocument,
    DividerBlock,
    DocumentInteraction,
    DocumentMeta,
    FormulaBlock,
    HeadingBlock,
    IconToken,
    KeyValueBlock,
    ListBlock,
    ListItem,
    ParagraphBlock,
    StepsBlock,
    TableBlock,
    WidgetBlock,
    parse_content_document,
)

__all__ = [
    "ActionKind",
    "ActionSpec",
    "ActionStyle",
    "CalloutBlock",
    "ChartBlock",
    "CodeBlock",
    "ContentBlock",
    "ContentDocument",
    "DividerBlock",
    "DocumentInteraction",
    "DocumentMeta",
    "FormulaBlock",
    "HeadingBlock",
    "IconToken",
    "KeyValueBlock",
    "ListBlock",
    "ListItem",
    "ParagraphBlock",
    "StepsBlock",
    "TableBlock",
    "WidgetBlock",
    "parse_content_document",
]
