"""Init.

Revision ID: b40a1e1618c5
Revises:
Create Date: 2026-08-19 16:02:13.584018
"""

# revision identifiers, used by Alembic.
revision = "b40a1e1618c5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database to the next version."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    """Downgrade the database to the previous version."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
