"""Baseline.

Revision ID: c48be75a5467
Revises: b40a1e1618c5
Create Date: 2026-08-19 16:05:58.951366
"""

# revision identifiers, used by Alembic.
revision = "c48be75a5467"
down_revision = "b40a1e1618c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database to the next version."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    """Downgrade the database to the previous version."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
